<a href="https://colab.research.google.com/github/ffayzullaev/Data_Science_MohirDev/blob/main/2_1_3_Arr_Or_Pr_1_Logical_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ma'lumotlar tahlili.
2.1. NumPy kutubxonasi bilan ishlash

NumPy kutubxonasini chaqirib olish

In [1]:
import numpy as np

2.1.3. Massivga yo'naltirilgan dasturlash

Mantiqiy shart operatorlarni massiv operator sifatida qo'llash

Shart operatori sifatida **where** dan foydalanish

Tassavur qiling bizda ikkita ma'lumotlar (massivlar) mavjud bular: **xarr** va **yarr**. Agarda shart **True**ni qanoatlantirsa **xarr** elementini qabul qilgan aksincha esa **yarr** elementini qabul qilgan yangi massiv hosil qilinsin.Tassavur qiling bizda ikkita ma'lumotlar (massivlar) mavjud bular: **xarr** va **yarr**. Agarda shart **True**ni qanoatlantirsa **xarr** elementini qabul qilgan aksincha esa **yarr** elementini qabul qilgan yangi massiv hosil qilinsin.

In [2]:
# Massivlar
xarr=np.array([1.1, 1.2, 1.3, 1.4, 1.5]) #xarr
yarr=np.array([2.1, 2.2, 2.3, 2.4, 2.5]) #yarr

In [3]:
#shart
cond=np.array([True, False, True, True, False])

In [4]:
#where
result=np.where(cond, xarr,yarr) # cond==True:xarr elementi, cond==False:yarr elementi
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [5]:
arr=np.random.randn(4,4) #(4,4) taxminiy massiv
arr

array([[ 2.44164665, -0.69406596, -0.56996356,  0.93926032],
       [ 0.67820751, -0.16711176, -0.24449653,  1.21644958],
       [ 0.05692866,  0.21382542, -0.800371  ,  0.78329731],
       [ 0.41952858, -0.28489006, -2.386953  ,  0.80641947]])

In [6]:
#where
results=np.where(arr<0, -2,2) #arr ning manfiy elementlarini -2 ga musbat elementlarini esa 2 ga almashtirish
results

array([[ 2, -2, -2,  2],
       [ 2, -2, -2,  2],
       [ 2,  2, -2,  2],
       [ 2, -2, -2,  2]])

In [10]:
results0=np.where(arr<0, -6,6)#arr ning manfiy elementlarini -6 ga musbat elementlarini esa 6 ga almashtitish
results0

array([[ 6, -6, -6,  6],
       [ 6, -6, -6,  6],
       [ 6,  6, -6,  6],
       [ 6, -6, -6,  6]])

In [9]:
results1=np.where(arr>0, 1,0)#arr ning manfiy elementlarini 0 ga musbat elementlarini esa 1 ga almashtitish
results1 

array([[1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 0, 1],
       [1, 0, 0, 1]])