<a href="https://colab.research.google.com/github/ffayzullaev/Data_Science_MohirDev/blob/main/2_1_2_Universal_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ma'lumotlar tahlili.
2.1. NumPy kutubxonasi bilan ishlash

NumPy kutubxonasini chaqirib olish

In [1]:
import numpy as np

2.1.2. Universal funksiyalar
Unary funksiyalar (bitta argument qabul qiluvchi funkisya)





**sqrt**, **square**, **exp**, **log**, **modf**, **sign**, **isnan** funksiyalarini ko'rib chiqamiz

In [3]:
arr = np.arange(10) #0dan 10 gacha bo'lgan elementlardan iborat massivlarni qaytaradi
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**sqrt** massivning xar bir elementini kvadrat ildizini qaytaradi

In [4]:
np.sqrt(arr) # arr nomli massivning barcha elementlaridan kvadrat ildiz qaytaradi

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

**square** massivning xar bir elementini kvadratga oshiradi

In [5]:
np.square(arr) #arr nomli massivning barcha elementlarini kvadratga oshiradi

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

**exp** massivning xar bir elementini kvadratga oshiradi 

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.exp(arr) #arr nomli massivning barcha elementlarini eksponentini qaytaradi 

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

**log**  massivning xar bir logorifimini hosoblaydi


In [8]:
np.log(arr[1:]) # arr nomli massivning 0-elementdan tashqari barcha logarifimini hisoblaydi(loge)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

**modf**  bu funksiya sonlarni butun va qoldiq qismlarini ajratib beruvchi funksiya

In [9]:
arr1=np.random.randn(6) # 6ta elementdan iborat taxminiy qiymatlarga ega massiv
arr1

array([ 0.761589  , -0.24619636,  0.76593602, -0.5784955 , -0.13752442,
       -2.31263144])

In [12]:
qoldiq, butun = np.modf(arr1) # arr1 ning elementlarini qoldiq va butun qismlarini ikkita massivga ajratib beradi

In [11]:
print(qoldiq)
print(butun)

[ 0.761589   -0.24619636  0.76593602 -0.5784955  -0.13752442 -0.31263144]
[ 0. -0.  0. -0. -0. -2.]


**sign** funksiyasi massiv elementlarini qiymat manfiy bo'lsa **-1** va aksincha musbat bo'lsa **1** ni qaytaradi

In [13]:
np.sign(arr1) #arr1 massivning elementlari ishoralarini "-1" va "1" ko'rinishida qaytaradi

array([ 1., -1.,  1., -1., -1., -1.])

**isnan** massivning elementlarida NaN ma'lumoti bo'lsa **True** qaytaradi va aksincha esa False qaytaradi

In [14]:
np.isnan(arr1)

array([False, False, False, False, False, False])

In [15]:
arr1[0]=np.NaN# 0-elementimizni nan ga almashtirdik

In [17]:
arr1

array([        nan, -0.24619636,  0.76593602, -0.5784955 , -0.13752442,
       -2.31263144])

In [18]:
np.isnan(arr1)

array([ True, False, False, False, False, False])

Binary funksiyalar (ikkita argument qabul qiluvchi funkisya)

**add**, **multiply**, **maximum** funksiyalarini ko'rib chiqamiz

**add** ikkita massivning mos elementlarini qo'shadi

In [19]:
# 2 ta massivni yaratib olamiz
arr2=np.random.randn(6)
arr3=np.random.randn(6)

In [20]:
arr2

array([ 0.17749037, -0.30664122,  0.72732459,  2.0419163 , -1.95223688,
       -0.92317093])

In [21]:
arr3

array([-0.0685785 ,  1.79721445, -1.44773006, -0.82073742, -0.41380711,
       -0.33716331])

In [22]:
np.add(arr2, arr3) # arr2 va arr3 ning elementlarini mos ravishda qo'shib beradi 

array([ 0.10891187,  1.49057323, -0.72040547,  1.22117888, -2.36604399,
       -1.26033424])

**multiply** ikkita massivning mos elementlarini ko'paytiradi

In [23]:
arr2

array([ 0.17749037, -0.30664122,  0.72732459,  2.0419163 , -1.95223688,
       -0.92317093])

In [24]:
arr3

array([-0.0685785 ,  1.79721445, -1.44773006, -0.82073742, -0.41380711,
       -0.33716331])

In [25]:
np.multiply(arr2,arr3) #arr2 va arr3 ning mos elementlarini ko'paytirib beradi

array([-0.01217202, -0.55110004, -1.05296966, -1.67587711,  0.80784951,
        0.31125936])

**maximum** ikkita massivning elementlarini taqqoslab ulardan kattasining qiymatini qaytaradi

In [26]:
np.maximum(arr2, arr3)

array([ 0.17749037,  1.79721445,  0.72732459,  2.0419163 , -0.41380711,
       -0.33716331])