<a href="https://colab.research.google.com/github/ffayzullaev/Data_Science_MohirDev/blob/main/2_1_3_Arr_Or_Pr_1_Math%26Stat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ma'lumotlar tahlili.

2.1. NumPy kutubxonasi bilan ishlash

NumPy kutubxonasini chaqirib olish

In [1]:
import numpy as np

2.1.3. Massivga yo'naltirilgan dasturlash

Matematik va Statistik usullarni qo'llash


In [2]:
#data
arr=np.random.randn(5,4) #(5,4) o'lchovli massiv (random)
arr

array([[ 2.6272861 , -1.59388078,  0.5219648 , -0.62680056],
       [-0.51091138,  0.09854444,  0.17631379,  0.40871643],
       [-0.55842713,  1.35685195, -0.49947271, -2.38852235],
       [-1.0439046 , -0.07051924, -0.28135969, -0.06659494],
       [ 2.85948747, -0.82307704,  0.09457043, -0.45246997]])

**sum** metodi

In [3]:
arr.sum() # arr ning barcha elementlarini yig'indisini hisoblab beradi

-0.7722049999410754

In [4]:
arr.sum() # arr ning barcha elementlarini yig'indisini hisoblab beradi

-0.7722049999410754

In [8]:
arr.sum(axis=1) # qatorlar yig'indisi

array([ 0.92856956,  0.17266327, -2.08957024, -1.46237847,  1.67851089])

In [9]:
arr.sum(axis=0) # ustunlar yig'indisi

array([ 3.37353046, -1.03208068,  0.01201661, -3.12567138])

**mean** metodi

In [10]:
#sodda ma'lumot
data=np.arange(5) # 0-5gacha bo'lgan elementlarda tashkil topgan massiv
data

array([0, 1, 2, 3, 4])

In [11]:
mean=np.sum(data)/len(data)
mean

2.0

In [12]:
#numpy mean
np.mean(data)

2.0

In [13]:
data.mean()


2.0

In [14]:
arr

array([[ 2.6272861 , -1.59388078,  0.5219648 , -0.62680056],
       [-0.51091138,  0.09854444,  0.17631379,  0.40871643],
       [-0.55842713,  1.35685195, -0.49947271, -2.38852235],
       [-1.0439046 , -0.07051924, -0.28135969, -0.06659494],
       [ 2.85948747, -0.82307704,  0.09457043, -0.45246997]])

In [16]:
np.mean(arr) # arr ning o'rtacha qiymati 

-0.03861024999705377

In [17]:
np.mean(arr, axis=1) # qator bo'yicha o'rtacha qiymatni qaytaradi

array([ 0.23214239,  0.04316582, -0.52239256, -0.36559462,  0.41962772])

In [18]:
np.mean(arr, axis=0) # ustun bo'yicha o'rtacha qiymatni qaytaradi

array([ 0.67470609, -0.20641614,  0.00240332, -0.62513428])

**cumsum** metodi

In [19]:
data 

array([0, 1, 2, 3, 4])

In [20]:
data.cumsum()


array([ 0,  1,  3,  6, 10])