<a href="https://colab.research.google.com/github/ffayzullaev/Data_Science_MohirDev/blob/main/2_1_3_Arr_Or_Pr_4Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ma'lumotlar tahlili.

2.1. NumPy kutubxonasi bilan ishlash

NumPy kutubxonasini chaqirib olish

In [2]:
import numpy as np

2.1.3. Massivga yo'naltirilgan dasturlash

Tartiblash (**Sorting**)

In [3]:
#data
arr=np.random.rand(4) #4ra taxminiy elementlardan tashkil topgan massiv
arr

array([0.46408743, 0.67647678, 0.45019722, 0.46258638])

**sort** funkiyasi

In [5]:
#1 usul 
sorted_arr=np.sort(arr) #arr massivni tartiblangan ko'rinishini sorted_arr  oylaydi
sorted_arr

array([0.45019722, 0.46258638, 0.46408743, 0.67647678])

In [6]:
#2 usul
arr.sort() #arr ning tartiblangan ko'rinishi
arr

array([0.45019722, 0.46258638, 0.46408743, 0.67647678])

In [7]:
#teskari tartiblash 
rev_arr= -np.sort(-arr) #teskari tartibdagi arr
rev_arr

array([0.67647678, 0.46408743, 0.46258638, 0.45019722])

In [10]:
# 2D array (massiv)
arr2d = np.random.rand(2,4) # (2,4) random massiv
arr2d

array([[0.84340334, 0.34612148, 0.94577545, 0.4221725 ],
       [0.06995539, 0.62245334, 0.79055778, 0.42271641]])

In [11]:
# axis = 0--> Qator
row_srt=np.sort(arr2d, axis=0) #arr2d ning xar bir qator bo'yicha tartiblangan ko'rinishi
row_srt

array([[0.06995539, 0.34612148, 0.79055778, 0.4221725 ],
       [0.84340334, 0.62245334, 0.94577545, 0.42271641]])

In [12]:
# axis = 1--> Ustun
col_srt=np.sort(arr2d, axis=1) # arr2d ning xar bir ustun bo'yicha tartiblangan ko'rinishi
col_srt

array([[0.34612148, 0.4221725 , 0.84340334, 0.94577545],
       [0.06995539, 0.42271641, 0.62245334, 0.79055778]])