<a href="https://colab.research.google.com/github/ffayzullaev/Data_Science_MohirDev/blob/main/42_NumPy_%D0%97%D0%B0%D0%B4%D0%B0%D1%87.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Импортировать NumPy под именем np

In [ ]:
import numpy as np

2.Напечатать версию и конфигурацию

In [ ]:
print(np.__version__)
np.show_config()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

3.Создать вектор (одномерный массив) размера 10, заполненный нулями

In [ ]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. Создать вектор размера 10, заполненный единицами

In [ ]:
z = np.ones(10)
print(z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


5.Создать вектор размера 10, заполненный числом 2.5


In [ ]:
z= np.full(10, 2.5)
print(z)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


6.Как получить документацию о функции numpy.add из командной строки?

In [ ]:
python3 -c "import numpy; numpy.info(numpy.add)"

7. Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [ ]:
z = np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


8.Создать вектор со значениями от 10 до 49


In [ ]:
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


9.Развернуть вектор (первый становится последним)

In [ ]:
z= np.arange(50)
z= z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


10. Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [ ]:
z= np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


11. Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [ ]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 2, 3, 4, 5, 8]),)


12.Создать 3x3 единичную матрицу

In [ ]:
z=np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


13.Создать массив 3x3x3 со случайными значениями

In [ ]:
z=np.random.random((3,3,3))
print(z)

[[[0.99384391 0.3489966  0.81140711]
  [0.41897403 0.80260593 0.78030629]
  [0.53020512 0.42376126 0.28114059]]

 [[0.29896282 0.98823305 0.65015682]
  [0.54737451 0.37283582 0.92798462]
  [0.02650523 0.86617248 0.97716595]]

 [[0.18924382 0.06988107 0.90221294]
  [0.20470833 0.41061729 0.8961106 ]
  [0.22508658 0.7342991  0.95723575]]]


14.Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [ ]:
Z=np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.01600760824657388 0.9815381366087939


15.Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [ ]:
Z = np.random.random(30)
m=Z.mean()
print(m)

0.5388567154847983


16.Создать матрицу с 0 внутри, и 1 на границах

In [ ]:
z = np.ones((10,10))
z[1:-1,1:-1]=0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


17.Выяснить результат следующих выражений

In [ ]:
0*np.nan
np.nan==np.nan
np.inf>np.nan
np.nan-np.nan
0.3==3*0.1

False

18.Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [ ]:
z=np.diag(np.arange(1,5), k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19.Создать 8x8 матрицу и заполнить её в шахматном порядке

In [ ]:
z=np.zeros((8,8), dtype=int)
z[1::2,::2]=1
z[::2,1::2]=1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20.Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [ ]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


21.Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [ ]:
z=np.tile(np.array([[0,1],[1,0]]), (4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22.Перемножить матрицы 5x3 и 3x2

In [ ]:
z=np.dot(np.ones((5,3)), np.ones((3,2)))
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


23.Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [ ]:
z=np.arange(11)
z[(3<z) & (z<=8)]*=-1
print(z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


24.Создать 5x5 матрицу со значениями в строках от 0 до 4

In [ ]:
z=np.zeros((5,5))
z+=np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


25.Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [ ]:
z=np.linspace(0,1,12)[1:-1]
print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


26.Отсортировать вектор

In [ ]:
z=np.random.random(10)
z.sort()
print(z)

[0.07745399 0.25182702 0.29349443 0.39833063 0.44097611 0.46319357
 0.58426393 0.70444805 0.7209231  0.83574098]


27.Проверить, одинаковы ли 2 numpy массива

In [ ]:
a=np.random.randint(0,2,5)
b=np.random.randint(0,2,5)
equal=np.allclose(a,b)
print(equal)

False


28.Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную

In [ ]:
z= np.random.random((10,2))
x,y=z[:,0], z[:,1]
r=np.hypot(x,y)
t=np.arctan2(y,x)
print(r)
print(t)

[0.89420593 0.94403276 0.82751727 0.73252834 0.72475149 0.94484244
 0.59873345 1.11142132 0.89485843 1.22552647]
[0.38952739 0.28817447 0.27115436 0.15757072 1.37089583 1.03170727
 0.43268117 0.51708485 0.25112938 0.66000437]


29.Заменить максимальный элемент на ноль

In [ ]:
z=np.random.random(10)
z[z.argmax()]=0
print(z)

[0.90040789 0.71132592 0.53208899 0.32409937 0.16217495 0.01170272
 0.78528643 0.         0.1967083  0.425526  ]


30.Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [ ]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

31.Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [ ]:
x=np.arange(8)
y=x+0.5
c=1.0/np.subtract.outer(x,y)
print(np.linalg.det(c))

3638.163637117973


32.Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)
  

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


33.Найти ближайшее к заданному значению число в заданном массиве

In [ ]:
z=np.arange(100)
v=np.random.uniform(0,100)
index=(np.abs(z-v)).argmin()
print(z[index])

60


34.Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b)

In [ ]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


35.Дан массив (100,2) координат, найти расстояние от каждой точки до каждой

In [ ]:
import scipy.spatial
z=np.random.random((10,2))
d=scipy.spatial.distance.cdist(z,z)
print(d)

[[0.         0.75393498 0.47025857 0.77897821 0.26133883 0.76693962
  0.5586375  0.2294331  0.79683559 0.59479285]
 [0.75393498 0.         0.67065126 0.94272941 0.4926596  0.69482505
  0.95289476 0.5733326  0.94798862 0.1592613 ]
 [0.47025857 0.67065126 0.         0.34452001 0.40967721 0.30562425
  0.28378188 0.29177521 0.3587954  0.55801847]
 [0.77897821 0.94272941 0.34452001 0.         0.75417643 0.28888495
  0.28673726 0.63278766 0.01951574 0.86188594]
 [0.26133883 0.4926596  0.40967721 0.75417643 0.         0.64587618
  0.6202514  0.13592011 0.76842228 0.33362402]
 [0.76693962 0.69482505 0.30562425 0.28888495 0.64587618 0.
  0.46963816 0.56091495 0.28581365 0.64592503]
 [0.5586375  0.95289476 0.28378188 0.28673726 0.6202514  0.46963816
  0.         0.48456149 0.30605799 0.8328684 ]
 [0.2294331  0.5733326  0.29177521 0.63278766 0.13592011 0.56091495
  0.48456149 0.         0.64816486 0.42087079]
 [0.79683559 0.94798862 0.3587954  0.01951574 0.76842228 0.28581365
  0.30605799 0.64816

36.Преобразовать массив из float в int

In [ ]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)

37.Отнять среднее из каждой строки в матрице

In [ ]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)

38.Отсортировать матрицу по n-ому столбцу

In [ ]:
Z = np.random.randint(0,10,(3,3))
n = 1  # Нумерация с нуля
print(Z)
print(Z[Z[:,n].argsort()])

[[1 6 5]
 [5 2 7]
 [1 6 8]]
[[5 2 7]
 [1 6 5]
 [1 6 8]]


39.Определить, есть ли в 2D массиве нулевые столбцы

In [ ]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


40.Посчитать ранг матрицы

In [ ]:
z=np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(z)

41.Найти наиболее частое значение в массиве

In [ ]:
z=np.random.randint(0,10,50)
print(np.bincount(z).argmax())

42. Написать игру "жизнь"

In [78]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N == 3) & (Z[1:-1,1:-1]==0)
    survive = ((N == 2) | (N == 3)) & (Z[1:-1,1:-1] == 1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100):
    print(Z)
    Z = iterate(Z)

[[1 1 0 ... 1 0 1]
 [1 1 1 ... 1 0 1]
 [1 0 1 ... 0 0 1]
 ...
 [1 1 0 ... 0 0 0]
 [1 1 0 ... 0 1 1]
 [0 0 1 ... 0 0 1]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 1 0 ... 1 1 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 1 1 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [