<a href="https://colab.research.google.com/github/ffayzullaev/Data_Science_MohirDev/blob/main/_1_Creating_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy kutubxonasini chaqirib olish

In [ ]:
import numpy as np

N-o'lchamli massiv (array)larga ishlov berish

Numpyda massiv yaratishning eng oson yo'llaridan biri bu **array** funksiyasi yordamida amalga oshiriladi. Va ushbu funksiya har qanday turdagi ketma-ket ma'lumotlarni qabul qilib, uni yangi Numpy arrayiga o'girib beradi.

In [ ]:
data1 = [3.5, 5, 8, -8, 78]#list
arr1 = np.array(data1) # array1

In [ ]:
arr1

array([ 3.5,  5. ,  8. , -8. , 78. ])

In [ ]:
data2 = (4, 5 , -89.5, 78, 54) #tuple
arr2 = np.array(data2)

In [ ]:
arr2

array([  4. ,   5. , -89.5,  78. ,  54. ])

Massiv o'lchami

In [ ]:
arr1.ndim #array1 ning o'chami

1

In [ ]:
arr2.ndim # array2 ning o'chami

1

Ikki va undan katta o'lchamli massivlar

In [ ]:
data3 = [[1, 2, 3, 4], [5, 6, 7, 8]] #list ichidagi list (nested list)
arr3 = np.array(data3) #array3

In [ ]:
data3

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [ ]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr3.ndim

2

In [ ]:
data4 = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]] #list ichidagi list
arr4 = np.array(data4) #array4

In [ ]:
data4

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]

In [ ]:
arr4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
arr4.ndim

2

# Darsimizni ikinchi qismi...

**shape**, **size** metodlari

**shape** metodi massivning qator va ustunlar sonini ko'rsatsa, **size** esa massivning elementlar sonini nomoyon etadi

In [ ]:
arr3.shape # qator va ustunlar sonini ko'rsatadi (q,u)

(2, 4)

In [ ]:
arr3.size #array3 ning elementlar soni

8

# N-o'chamli massivlar yaratishning boshqa usullari

**zeros** va **ones** funlsiyalari yordamida massivlar yaratish

In [34]:
arr4 = np.zeros((2, 4)) # barcha elementlari 0 ga teng (2,4)
arr4


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr5 = np.ones((2,4)) #barcha elementlari 1 ga teng (2,4)
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**arange** funksiyasi yordamida yaratish

In [35]:
arr6 = np.arange(4, 20 , 2) #4 dan 20 gacha bo'lgan qiymatlarni 2 qadam blan massivga joylab beradi
arr6

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr7 = np.arange(20) # 0dan 20 gacha bo'gan qiymatlarni 1 qadam blan massivga joylab beradi
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])