<a href="https://colab.research.google.com/github/ffayzullaev/Data_Science_MohirDev/blob/main/_3_indexing%26Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

2.1.1 N-O'lvhamli massiv (array)larga ishlov berish

indeks va kesib olish asoslari

In [4]:
arr = np.arange(10,100,10)
arr[-9]

10

In [6]:
arr[3:5]#3dan 5gacha bo'lgan elementlarni kesib olib qaytaradi

array([40, 50])

Numpy kutubxonasida massivning kesib olingan qismga o'zgartirish kiritilsa, asosiy manba massivga ta'sir qiladi.

In [7]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
sliced_arr=arr[3:5]
sliced_arr[:]=0
sliced_arr

array([0, 0])

In [11]:
arr

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

**copy** usuli haqida

In [12]:
arr1 = np.arange(10,100,10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [15]:
sliced_arr1=arr1[3:5].copy()
sliced_arr1[:]=0
sliced_arr1

array([0, 0])

In [16]:
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

2-o'lchamli (2d array) massivlarga indeks va kesib olish

In [19]:
arr2d=np.array([[1,2,3,],[4,5,6],[7,8,9]]) #(3,3) o;lchamli massiv
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr2d[1,1]

5

In [22]:
arr2d[2,2]

9

2-o'chamli massivlarning bir nechta elementlarini kesib olish

In [23]:
sl_arr2d = arr2d[2,1:3]
sl_arr2d

array([8, 9])

3-o'lchamli massivlarda indeks va kesib olish asoslari

In [24]:
#3D array
arr3d=np.array([[[0,1,2],
                 [3,4,5],
                 [6,7,8]],
                [[9,10,11],
                 [12,13,14],
                 [15,16,17]],
                [[18,19,20],
                 [21,22,23],
                 [24,25,26]]])
arr3d 

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [26]:
arr3d[0][1,1]

4

In [29]:
arr3d[1][2,1:3]

array([16, 17])

In [30]:
arr3d[2][0,0:2]

array([18, 19])