<a href="https://colab.research.google.com/github/ffayzullaev/Data_Science_MohirDev/blob/main/_4_Boolean_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ma'lumotlar tahlili.
2.1. NumPy kutubxonasi bilan ishlash
NumPy kutubxonasini chaqirib olish

In [1]:
import numpy as np

2.1.1 N-o'lchamli massiv(array)larga ishlov berish

Boolean indekslash

In [2]:
#Ismlar
names=np.array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U8')

In [3]:
#data
data=np.random.randn(7,4)
data

array([[-0.2921507 ,  2.18277002,  0.78254793,  2.77510495],
       [ 1.55463451, -1.25605343,  1.36216416,  0.99543817],
       [ 0.80857082,  0.09432598, -1.09863432, -1.30987374],
       [ 0.98174395,  0.09566609, -0.76866342,  0.27419973],
       [ 0.72401901, -0.07459557, -0.30765223, -0.34423618],
       [-2.10198317,  0.8940882 ,  0.56004376, -0.30234889],
       [-0.19514295, -1.72507688,  1.10361484,  1.18339899]])

In [4]:
names=='Hasan'

array([ True, False, False, False,  True, False, False])

In [5]:
data[names=='Hasan'] #Hasanga tegishli barcha ma'lmotlarni ajratib olsh

array([[-0.2921507 ,  2.18277002,  0.78254793,  2.77510495],
       [ 0.72401901, -0.07459557, -0.30765223, -0.34423618]])

In [9]:
data[names=='Elyor'] #Elyorga tegishli barcha ma'lmotlarni ajratib olsh

array([[ 0.98174395,  0.09566609, -0.76866342,  0.27419973],
       [-0.19514295, -1.72507688,  1.10361484,  1.18339899]])

In [8]:
data[names=='Mirzabek']#Mirzabekga tegishli barcha ma'lmotlarni ajratib olsh

array([[ 0.80857082,  0.09432598, -1.09863432, -1.30987374]])

In [10]:
data[names=='Hasan', 2:] #Hasanga tegishli oxirgi ikkita ustundagi ma'lumotlarni ajratib olish

array([[ 0.78254793,  2.77510495],
       [-0.30765223, -0.34423618]])

In [12]:
data[names=='Husan', 1:3] #Husnga tegishli [1:3] ustundagi ma'lumotlarni ajratib olish

array([[-1.25605343,  1.36216416]])

In [14]:
data[names=='Javohir', 0:3] #Javohirga tegishli [0:3] ustundagi ma'umotlarni ajratib olish

array([[-2.10198317,  0.8940882 ,  0.56004376]])

In [15]:
data[names!='Hasan'] #(!=)  Hasndan tashqari barcha insonlarning ma'lumotlarni ajratib olish

array([[ 1.55463451, -1.25605343,  1.36216416,  0.99543817],
       [ 0.80857082,  0.09432598, -1.09863432, -1.30987374],
       [ 0.98174395,  0.09566609, -0.76866342,  0.27419973],
       [-2.10198317,  0.8940882 ,  0.56004376, -0.30234889],
       [-0.19514295, -1.72507688,  1.10361484,  1.18339899]])

In [17]:
data[~(names=='Hasan')] #(~) yuqoridagi cell bilan bir xil natijani berar ekan

array([[ 1.55463451, -1.25605343,  1.36216416,  0.99543817],
       [ 0.80857082,  0.09432598, -1.09863432, -1.30987374],
       [ 0.98174395,  0.09566609, -0.76866342,  0.27419973],
       [-2.10198317,  0.8940882 ,  0.56004376, -0.30234889],
       [-0.19514295, -1.72507688,  1.10361484,  1.18339899]])

In [19]:
print(names)
print(data)

['Hasan' 'Husan' 'Mirzabek' 'Elyor' 'Hasan' 'Javohir' 'Elyor']
[[-0.2921507   2.18277002  0.78254793  2.77510495]
 [ 1.55463451 -1.25605343  1.36216416  0.99543817]
 [ 0.80857082  0.09432598 -1.09863432 -1.30987374]
 [ 0.98174395  0.09566609 -0.76866342  0.27419973]
 [ 0.72401901 -0.07459557 -0.30765223 -0.34423618]
 [-2.10198317  0.8940882   0.56004376 -0.30234889]
 [-0.19514295 -1.72507688  1.10361484  1.18339899]]


In [21]:
mask = (names=='Hasan') | (names=='Husan') # " | " -or (yoki)
mask

array([ True,  True, False, False,  True, False, False])

In [22]:
data[mask] #Hasan va Husanga tegishli ma'lumotlarni ajratib olish

array([[-0.2921507 ,  2.18277002,  0.78254793,  2.77510495],
       [ 1.55463451, -1.25605343,  1.36216416,  0.99543817],
       [ 0.72401901, -0.07459557, -0.30765223, -0.34423618]])

In [23]:
data

array([[-0.2921507 ,  2.18277002,  0.78254793,  2.77510495],
       [ 1.55463451, -1.25605343,  1.36216416,  0.99543817],
       [ 0.80857082,  0.09432598, -1.09863432, -1.30987374],
       [ 0.98174395,  0.09566609, -0.76866342,  0.27419973],
       [ 0.72401901, -0.07459557, -0.30765223, -0.34423618],
       [-2.10198317,  0.8940882 ,  0.56004376, -0.30234889],
       [-0.19514295, -1.72507688,  1.10361484,  1.18339899]])

In [25]:
data[data<0]=0
data

array([[0.        , 2.18277002, 0.78254793, 2.77510495],
       [1.55463451, 0.        , 1.36216416, 0.99543817],
       [0.80857082, 0.09432598, 0.        , 0.        ],
       [0.98174395, 0.09566609, 0.        , 0.27419973],
       [0.72401901, 0.        , 0.        , 0.        ],
       [0.        , 0.8940882 , 0.56004376, 0.        ],
       [0.        , 0.        , 1.10361484, 1.18339899]])