<a href="https://colab.research.google.com/github/ffayzullaev/Data_Science_MohirDev/blob/main/_5_Transpossing%26Swapping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ma'lumotlar tahlili.
2.1. NumPy kutubxonasi bilan ishlash
NumPy kutubxonasini chaqirib olish

In [1]:
import  numpy as np

2.1.1. N-o'lchamli massiv (array)larga ishlov berish

Massivlar pozitsiyasini ko'chirish **Transpose** va o'qlar o'rnini almashtirish **Swapping** **axes**

**reshape** metodi

In [4]:
A = np.arange(6).reshape(3,2) # A massib elementlari 0 dan 6 gacha, shape (3,2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

**Transpose**

In [5]:
A.T # A massivning transpose ko'rinishi beradi

array([[0, 2, 4],
       [1, 3, 5]])

**swapping** **axes**

In [6]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
A.swapaxes(1,0) # A massivning transpose ko'rinishini beradi

array([[0, 2, 4],
       [1, 3, 5]])

**Transpose**ning ishlatilishiga bir misol AA^T 

In [8]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [10]:
np.dot(A,A.T) # AA^T hosil bo'lgan massiv

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])