<a href="https://colab.research.google.com/github/ffayzullaev/Data_Science_MohirDev/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ma'lumotlar tahlili. NumPy kutubxonasi.

Fayllar bilan ishlash

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**np.save()** fayl yatarib olish

In [4]:
np.save('data',arr)

**np.load()** yaratilgan faylni o'qish

In [5]:
arr2=np.load('data.npy')

In [6]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr1=np.arange(20) 

**np.savez()**  birdan ko'prok fayllarni saqlash 

In [8]:
np.savez('arrays', a=arr, b=arr1)

In [9]:
arrays=np.load('arrays.npz')

In [10]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

**np.save_compressed** fayllarni arraylarni siqilgan holatda saqlaydi

In [12]:
np.savez_compressed('array_comp.npz', a=arr, b=arr1)